"""empty message

Revision ID: 7da4e99d2af8
Revises: 
Create Date: 2023-12-07 14:09:45.701378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da4e99d2af8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('tgid', sa.BigInteger(), nullable=True),
    sa.Column('tg_confirm_guid', sa.String(), nullable=False),
    sa.Column('dvv', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_confirm_guid'),
    sa.UniqueConstraint('tgid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('utbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_number', sa.String(), nullable=False),
    sa.Column('car_going_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('car_going_place', sa.String(), nullable=False),
    sa.Column('car_info', sa.String(), nullable=False),
    sa.Column('truck_info', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('executor', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_phone', sa.String(), nullable=True),
    sa.Column('add_by_user_id', sa.Integer(), nullable=True),
    sa.Column('dkr', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kr_by_user_id', sa.Integer(), nullable=True),
    sa.Column('dvv', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['add_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kr_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utbs_car_info'), 'utbs', ['car_info'], unique=False)
    op.create_index(op.f('ix_utbs_license_plate'), 'utbs', ['license_plate'], unique=False)
    op.create_index(op.f('ix_utbs_note'), 'utbs', ['note'], unique=False)
    op.create_index(op.f('ix_utbs_owner_phone'), 'utbs', ['owner_phone'], unique=False)
    op.create_table('photos',
    sa.Column('utb_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dvv', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utb_id'], ['utbs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_utb_id'), 'photos', ['utb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_utb_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_utbs_owner_phone'), table_name='utbs')
    op.drop_index(op.f('ix_utbs_note'), table_name='utbs')
    op.drop_index(op.f('ix_utbs_license_plate'), table_name='utbs')
    op.drop_index(op.f('ix_utbs_car_info'), table_name='utbs')
    op.drop_table('utbs')
    op.drop_table('users')
    # ### end Alembic commands ###
